- name: Open Port 8001
  hosts: localhost
  connection: local

  vars:
    myResourceGroup: ansible
    myNetworkSecurityGroup: ansible-production-nsg

  tasks:
  - name: Create Network Security Group that allows port8001
    azure_rm_securitygroup:
      resource_group: "{{ myResourceGroup}}"
      name: "{{ myNetworkSecurityGroup }}"
      rules:
        - name: Port8001
          protocol: Tcp
          destination_port_range: 8001
          access: Allow
          priority: 1003
          direction: Inbound
