- name: Configure Node VM
  hosts: azure
  user: azureuser
  become: no

  vars:
    myResourceGroup: ansible
    myVM: production-node

  tasks:
  - name: Copy startKube.sh to Node
    copy:
     src: ./startKube.sh
     dest: /home/azureuser/startKube.sh

  - name: Edit Permissions
    command: chmod +x startKube.sh

  - name: Deploy Container
    command: ./startKube.sh
